[package]
name = "devkit"
version = "0.1.1"
description = "DevKit — cross-platform developer utilities desktop app"
authors = ["kezlo"]
edition = "2021"

[lib]
name = "devkit_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api", "tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bcrypt = "0.15"
jsonwebtoken = "9"
base64 = "0.22"
tauri-plugin-dialog = "2"
